package com.rotdex.utils

import androidx.compose.ui.graphics.Color
import kotlin.math.abs

/**
 * Utility functions for avatar generation
 *
 * Provides functions to:
 * - Extract 2-letter initials from player names
 * - Generate consistent hash-based colors for avatars
 *
 * Used by AvatarView composable for rendering player avatars
 */
object AvatarUtils {

    /**
     * Extract 2-letter initials from a player name
     *
     * Extraction rules (in order of priority):
     * 1. Two words: First letter of each word (e.g., "John Doe" → "JD")
     * 2. Hyphenated: First letter of each part (e.g., "player-abc" → "PA")
     * 3. CamelCase: First two capital letters (e.g., "JohnDoe" → "JD")
     * 4. Single word: First two letters (e.g., "Player" → "PL")
     * 5. Single character: Repeat twice (e.g., "X" → "XX")
     * 6. Empty/invalid: Default "??"
     *
     * All initials are returned in uppercase.
     *
     * @param playerName The player name to extract initials from
     * @return Two-letter initials in uppercase
     */
    fun getInitials(playerName: String): String {
        // Handle empty or whitespace-only names
        if (playerName.isBlank()) {
            return "??"
        }

        val trimmed = playerName.trim()

        // Try splitting by spaces (handles "John Doe")
        val spaceParts = trimmed.split(" ").filter { it.isNotBlank() }
        if (spaceParts.size >= 2) {
            val first = spaceParts[0].firstOrNull { it.isLetter() }?.uppercaseChar() ?: '?'
            val second = spaceParts[1].firstOrNull { it.isLetter() }?.uppercaseChar() ?: '?'
            return "$first$second"
        }

        // Try splitting by hyphens (handles "player-abc123")
        val hyphenParts = trimmed.split("-").filter { it.isNotBlank() }
        if (hyphenParts.size >= 2) {
            val first = hyphenParts[0].firstOrNull { it.isLetter() }?.uppercaseChar() ?: '?'
            val second = hyphenParts[1].firstOrNull { it.isLetter() }?.uppercaseChar() ?: '?'
            return "$first$second"
        }

        // Try extracting capital letters for CamelCase (handles "JohnDoe")
        val capitals = trimmed.filter { it.isUpperCase() }
        if (capitals.length >= 2) {
            return capitals.take(2)
        }

        // Fallback: Extract first two letters
        val letters = trimmed.filter { it.isLetter() }
        return when {
            letters.length >= 2 -> letters.take(2).uppercase()
            letters.length == 1 -> (letters[0].toString() + letters[0].toString()).uppercase()
            else -> "??"
        }
    }

    /**
     * Generate a consistent color for a player name using hash-based HSL generation
     *
     * The color is generated by:
     * 1. Hashing the player name (consistent for same name)
     * 2. Converting hash to HSL color space
     * 3. Using fixed saturation (70%) and lightness (50%) for vibrant colors
     * 4. Varying only the hue based on hash
     *
     * This ensures:
     * - Same name always gets same color
     * - Different names get different colors
     * - All colors are vibrant and visually pleasing
     * - Good color diversity across different names
     *
     * @param playerName The player name to generate a color for
     * @return A consistent Color based on the name hash
     */
    fun getColorFromName(playerName: String): Color {
        // Generate hash from player name (consistent for same name)
        val hash = playerName.hashCode()

        // Use hash to generate hue (0-360 degrees)
        // abs() ensures positive value, % 360 keeps it in valid range
        val hue = abs(hash) % 360

        // Fixed saturation and lightness for vibrant, consistent colors
        val saturation = 0.70f
        val lightness = 0.50f

        // Convert HSL to RGB Color
        return hslToColor(hue.toFloat(), saturation, lightness)
    }

    /**
     * Convert HSL color space to RGB Color
     *
     * @param hue Hue in degrees (0-360)
     * @param saturation Saturation (0-1)
     * @param lightness Lightness (0-1)
     * @return RGB Color
     */
    private fun hslToColor(hue: Float, saturation: Float, lightness: Float): Color {
        val h = hue / 360f
        val s = saturation
        val l = lightness

        val c = (1 - abs(2 * l - 1)) * s
        val x = c * (1 - abs((h * 6) % 2 - 1))
        val m = l - c / 2

        val (r1, g1, b1) = when {
            h < 1f / 6f -> Triple(c, x, 0f)
            h < 2f / 6f -> Triple(x, c, 0f)
            h < 3f / 6f -> Triple(0f, c, x)
            h < 4f / 6f -> Triple(0f, x, c)
            h < 5f / 6f -> Triple(x, 0f, c)
            else -> Triple(c, 0f, x)
        }

        return Color(
            red = (r1 + m).coerceIn(0f, 1f),
            green = (g1 + m).coerceIn(0f, 1f),
            blue = (b1 + m).coerceIn(0f, 1f),
            alpha = 1f
        )
    }
}
